### ISSUE TITLE
Compiler help?

### ISSUE THREAD

**Issue by helloitu** [fail0verflow/ps4-kexec#17]
ok, so, win 10 x64, try mingw64 & mingw32, not work, what try now?

**Comment by helloitu** [comment]
any compiler settings or tutorial? sorry for be an newbie.

**Comment by shuffle2** [comment]
try `git pull` and compile again

**Comment by helloitu** [comment]
thx for helping shuffle

kernel.c: In function 'kernel_hook_install':
kernel.c:174:19: error: left shift count >= width of type [-Werror=shift-count-overflow]
     if (!(t & (1L << 63))) {
                   ^~
In file included from kernel.h:14:0,
                 from kernel.c:11:
types.h:41:5: error: static assertion failed: "size of struct jmp_t != 14"
     _Static_assert(sizeof( struc ) == (size), "size of " #struc " != " #size )
     ^
kernel.c:196:9: note: in expansion of macro 'ASSERT_STRSIZE'
         ASSERT_STRSIZE(struct jmp_t, 14);
         ^~~~~~~~~~~~~~
types.h:41:5: error: static assertion failed: "size of struct jmp_t != 5"
     _Static_assert(sizeof( struc ) == (size), "size of " #struc " != " #size )
     ^
kernel.c:207:9: note: in expansion of macro 'ASSERT_STRSIZE'
         ASSERT_STRSIZE(struct jmp_t, 5);
         ^~~~~~~~~~~~~~
In file included from kernel.c:11:0:
kernel.c: In function 'kernel_init':
kernel.h:25:21: error: left shift count >= width of type [-Werror=shift-count-overflow]
  ((unsigned long)-1 << 47) | \
                     ^
kernel.c:298:22: note: in expansion of macro 'KVADDR'
     kern.kern_base = KVADDR(0x1ff, 0x1fe, 0, 0); // 0xffffffff80000000
                      ^~~~~~
kernel.h:26:23: error: left shift count >= width of type [-Werror=shift-count-overflow]
  ((unsigned long)(l4) << PML4SHIFT) | \
                       ^
kernel.c:298:22: note: in expansion of macro 'KVADDR'
     kern.kern_base = KVADDR(0x1ff, 0x1fe, 0, 0); // 0xffffffff80000000
                      ^~~~~~
kernel.h:25:21: error: left shift count >= width of type [-Werror=shift-count-overflow]
  ((unsigned long)-1 << 47) | \
                     ^
kernel.c:304:22: note: in expansion of macro 'KVADDR'
     kern.dmap_base = KVADDR(DMPML4I, DMPDPI, 0, 0);
                      ^~~~~~
kernel.h:26:23: error: left shift count >= width of type [-Werror=shift-count-overflow]
  ((unsigned long)(l4) << PML4SHIFT) | \
                       ^
kernel.c:304:22: note: in expansion of macro 'KVADDR'
     kern.dmap_base = KVADDR(DMPML4I, DMPDPI, 0, 0);
                      ^~~~~~
cc1.exe: all warnings being treated as errors

**Comment by shuffle2** [comment]
your compiler is still confused about sizes of integral types. I recommend just using normal gcc in WSL https://docs.microsoft.com/en-us/windows/wsl/install-win10
or some other sane gcc version...or figure out how to make mingw work.

**Comment by helloitu** [comment]
fixed using WSL, love u shuffle <3
